name: libusb
description: Dart wrapper via `dart:ffi` for https://github.com/libusb/libusb
version: 0.3.23+2
homepage: https://github.com/woodemi/libusb.dart

environment:
  sdk: '>=2.13.0 <3.0.0'

platforms:
  linux:
  macos:
  windows:

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  pedantic: ^1.10.0
  ffigen: ^3.0.0
  test: ^1.16.3
  convert: ^3.0.0

ffigen:
  name: Libusb
  description: Bindings to `libusb.h`.
  output: 'lib/libusb.dart'
  headers:
    entry-points:
      - 'libusb-1.0/libusb.h'
    include-directives: # include only these header files and necessary structs from other header files
      - '**libusb.h'
